name: Scraper Diario Frávega

on:
  schedule:
    # Se ejecuta a las 9:00 AM UTC (6:00 AM Arg) los LUNES (1) y JUEVES (4)
    - cron: '0 9 * * 1,4'
  workflow_dispatch: 

jobs:
  ejecutar-scraper:
    runs-on: ubuntu-latest 

    steps:
    - name: Descargar el repositorio
      uses: actions/checkout@v4 

    - name: Instalar Python
      uses: actions/setup-python@v5 
      with:
        python-version: '3.13.7'

    - name: Instalar librerías
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Correr el Scraper
      env:
        # Acá inyectamos la clave secreta de forma segura
        SCRAPER_API_KEY: ${{ secrets.SCRAPER_API_KEY }}
      run: python scraper/Fravega_Completo.py

    - name: Guardar los datos en el repositorio
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'actions@github.com'
        git add .
        git commit -m "🤖 Actualización bi-semanal de precios y limpieza" || echo "No hay cambios para subir"
        git push
